(define (problem bw_6_p01)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 b6 - block)
  (:init (emptyhand) (on-table b1) (on b2 b1) (on-table b3) (on-table b4) (on b5 b4) (on b6 b5) (clear b2) (clear b3) (clear b6))
  (:goal (and (emptyhand) (on-table b1) (on b2 b5) (on b3 b1) (on b4 b3) (on-table b5) (on b6 b4) (clear b2) (clear b6)))
  (:metric minimize (total-cost))
)
