(define (problem bw_6_p02)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 b6 - block)
  (:init (emptyhand) (on b1 b2) (on b2 b5) (on b3 b4) (on-table b4) (on-table b5) (on b6 b3) (clear b1) (clear b6))
  (:goal (and (emptyhand) (on-table b1) (on b2 b1) (on b3 b4) (on-table b4) (on-table b5) (on-table b6) (clear b2) (clear b3) (clear b5) (clear b6)))
  (:metric minimize (total-cost))
)
