(define (problem bw_7_p04)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 b6 b7 - block)
  (:init (emptyhand) (on-table b1) (on-table b2) (on b3 b4) (on b4 b2) (on-table b5) (on-table b6) (on-table b7) (clear b1) (clear b3) (clear b5) (clear b6) (clear b7))
  (:goal (and (emptyhand) (on b1 b7) (on-table b2) (on b3 b6) (on b4 b1) (on-table b5) (on b6 b5) (on-table b7) (clear b2) (clear b3) (clear b4)))
  (:metric minimize (total-cost))
)
