(define (problem bw_8_p06)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 - block)
  (:init (emptyhand) (on-table b1) (on b2 b1) (on b3 b5) (on b4 b3) (on b5 b8) (on b6 b2) (on-table b7) (on-table b8) (clear b4) (clear b6) (clear b7))
  (:goal (and (emptyhand) (on b1 b3) (on b2 b4) (on b3 b7) (on b4 b1) (on b5 b2) (on-table b6) (on-table b7) (on-table b8) (clear b5) (clear b6) (clear b8)))
  (:metric minimize (total-cost))
)
