(define (problem bw_9_p07)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 - block)
  (:init (emptyhand) (on-table b1) (on-table b2) (on b3 b6) (on-table b4) (on b5 b2) (on-table b6) (on b7 b8) (on b8 b3) (on b9 b1) (clear b4) (clear b5) (clear b7) (clear b9))
  (:goal (and (emptyhand) (on b1 b5) (on-table b2) (on b3 b1) (on-table b4) (on b5 b9) (on b6 b3) (on-table b7) (on-table b8) (on b9 b7) (clear b2) (clear b4) (clear b6) (clear b8)))
  (:metric minimize (total-cost))
)
