(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants RR VG KO MZ AH YX XO OD ON GO )
 (:predicates 
	 (WH ?X ) 
	 (XJ ?X ) 
	 (YT ?X ) 
	 (ZJ ?X ?Y ) 
(clear)
(not-clear)
 )
(:action XHG
 :parameters (?X ?Y )
 :precondition (and 
		 (WH ?Y) 
		 (ZJ ?Y ?Y) 
  )
 :effect (probabilistic 
		 47/100 (and (ZJ ?X ?X) (not (WH ?Y)) (WH ?X) (not (ZJ ?Y ?Y)) )  
		 9/100 (and (not (ZJ ?Y ?Y)) )  
		 28/100 (and (not (WH ?Y)) )  
		 6/100 (and (YT ?Y) (XJ ?X) (not (ZJ ?Y ?Y)) )  
		 10/100 (and (XJ ?Y) (not (ZJ ?Y ?Y)) (ZJ ?X ?Y) )  
          )
 )
(:action BRZ
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (XJ ?Z) 
		 (WH ?Y) 
		 (XJ ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (WH ?Y)) (YT ?Y) (ZJ ?Y ?Z) (YT ?X) )  
          )
 )
(:action YEV
 :parameters (?X ?Y )
 :precondition (and 
		 (ZJ ?Y ?X) 
		 (ZJ ?X ?Y) 
		 (YT ?Y) 
		 (XJ ?X) 
  )
 :effect (probabilistic 
		 58/100 (and (WH ?Y) )  
		 42/100 (and (XJ ?Y) )  
          )
 )
(:action OGF
 :parameters (?X ?Y )
 :precondition (and 
		 (ZJ ?X ?X) 
  )
 :effect (probabilistic 
		 76/100 (and (not (ZJ ?X ?X)) (WH ?Y) )  
		 1/100 (and (YT ?X) )  
		 7/100 (and (not (ZJ ?X ?X)) (YT ?Y) )  
		 16/100 (and (XJ ?Y) (not (ZJ ?X ?X)) (YT ?Y) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (WH ?x)) 
      (not (XJ ?x)) 
      (not (YT ?x)) 
      (not (ZJ ?x RR)) 
      (not (ZJ ?x VG)) 
      (not (ZJ ?x KO)) 
      (not (ZJ ?x MZ)) 
      (not (ZJ ?x AH)) 
      (not (ZJ ?x YX)) 
      (not (ZJ ?x XO)) 
      (not (ZJ ?x OD)) 
      (not (ZJ ?x ON)) 
      (not (ZJ ?x GO)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(ZJ AH VG) 
(ZJ OD KO) 
(ZJ ON RR) 
(XJ VG) 
(XJ ON) 
(YT XO) 
(YT RR) 
(YT YX) 
(ZJ MZ VG) 
(YT KO) 
(XJ AH) 
(ZJ ON AH) 
(ZJ RR VG) 
(YT GO) 
(WH KO) 
(YT VG) 
(ZJ OD XO) 
(WH VG) 
)))
