(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants ZH YH ET ZB QX DJ XT EM CE AZ )
 (:predicates 
	 (MU ?X ) 
	 (YK ?X ) 
	 (TM ?X ?Y ) 
	 (DW ?X ?Y ) 
(clear)
(not-clear)
 )
(:action EWQ
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (DW ?Y ?Z) 
  )
 :effect (probabilistic 
		 100/100 (and (MU ?Z) (DW ?X ?Y) )  
          )
 )
(:action CWL
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (DW ?X ?Z) 
		 (TM ?Z ?Z) 
  )
 :effect (probabilistic 
		 14/100 (and (YK ?Y) (MU ?Z) )  
		 65/100 (and (not (TM ?Z ?Z)) (YK ?X) (MU ?Z) (MU ?Y) )  
		 21/100 (and (MU ?X) (MU ?Z) (not (DW ?X ?Z)) )  
          )
 )
(:action UBG
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (DW ?X ?Y) 
		 (MU ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (MU ?X) (not (DW ?X ?Y)) (TM ?Z ?X) )  
          )
 )
(:action NFP
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (YK ?X) 
		 (DW ?X ?X) 
		 (MU ?X) 
		 (MU ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (TM ?Y ?X) (YK ?Z) )  
          )
 )
(:action WOP
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (YK ?Z) 
		 (MU ?Z) 
		 (DW ?Z ?X) 
  )
 :effect (probabilistic 
		 52/100 (and (not (DW ?Z ?X)) )  
		 23/100 (and (not (MU ?Z)) (not (YK ?Z)) )  
		 1/100 (and (not (DW ?Z ?X)) (TM ?Z ?Y) (not (MU ?Z)) (not (YK ?Z)) )  
		 24/100 (and (not (DW ?Z ?X)) (not (MU ?Z)) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (MU ?x)) 
      (not (YK ?x)) 
      (not (TM ?x ZH)) 
      (not (TM ?x YH)) 
      (not (TM ?x ET)) 
      (not (TM ?x ZB)) 
      (not (TM ?x QX)) 
      (not (TM ?x DJ)) 
      (not (TM ?x XT)) 
      (not (TM ?x EM)) 
      (not (TM ?x CE)) 
      (not (TM ?x AZ)) 
      (not (DW ?x ZH)) 
      (not (DW ?x YH)) 
      (not (DW ?x ET)) 
      (not (DW ?x ZB)) 
      (not (DW ?x QX)) 
      (not (DW ?x DJ)) 
      (not (DW ?x XT)) 
      (not (DW ?x EM)) 
      (not (DW ?x CE)) 
      (not (DW ?x AZ)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(DW ZH CE) 
(DW ZH XT) 
(TM CE YH) 
(YK EM) 
(DW ZH AZ) 
(MU YH) 
(MU QX) 
(TM YH AZ) 
(TM AZ DJ) 
(TM AZ ET) 
(MU EM) 
(YK ET) 
(DW AZ ZB) 
(TM ZB ZB) 
(DW ET ZH) 
(TM ET YH) 
(TM DJ EM) 
(DW EM CE) 
(TM EM EM) 
(MU AZ) 
(TM EM XT) 
(DW EM ZH) 
)))
