(define (problem random-problem832) 
 (:domain prob_domain) 
 (:init 
(not-clear)
(DW ZH CE) (DW ZH XT) (TM CE YH) (YK EM) (DW ZH AZ) (MU YH) (MU QX) (TM YH AZ) (TM AZ DJ) (TM AZ ET) (MU EM) (YK ET) (DW AZ ZB) (TM ZB ZB) (DW ET ZH) (TM ET YH) (TM DJ EM) (DW EM CE) (TM EM EM) (MU AZ) (TM EM XT) (DW EM ZH)  
)
 (:goal (and 
(TM ET  ZH ) 
(TM YH  ET ) 
(TM ET  AZ ) 
(TM YH  XT ) 
(DW QX  QX ) 
(TM CE  ZH ) 
(TM QX  ZH ) 
(DW YH  QX ) 
(DW EM  QX ) 
(DW ZB  YH ) 
(TM ZB  YH ) 
(DW CE  QX ) 
(TM QX  ZB ) 
(TM ZH  DJ ) 
(TM YH  QX ) 
(DW ET  QX ) 
(TM YH  EM ) 
(DW YH  ET ) 
))
)
