(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants WI UK YB ZJ KO AB OE MC SQ CH )
 (:predicates 
	 (VC ?X ) 
	 (OU ?X ?Y ) 
	 (AZ ?X ?Y ) 
	 (SY ?X ?Y ) 
	 (YM ?X ) 
(clear)
(not-clear)
 )
(:action IXY
 :parameters (?X ?Y )
 :precondition (and 
		 (OU ?X ?Y) 
		 (VC ?X) 
  )
 :effect (probabilistic 
		 43/100 (and (SY ?Y ?X) (VC ?Y) (SY ?X ?Y) )  
		 57/100 (and (SY ?Y ?X) )  
          )
 )
(:action WTD
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (YM ?Y) 
		 (OU ?X ?Z) 
		 (AZ ?Y ?Z) 
  )
 :effect (probabilistic 
		 91/100 (and (AZ ?Z ?X) )  
		 6/100 (and (OU ?Y ?Y) )  
		 3/100 (and (SY ?Y ?X) (not (AZ ?Y ?Z)) (not (YM ?Y)) )  
          )
 )
(:action UVX
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (SY ?X ?Z) 
		 (OU ?X ?Y) 
		 (VC ?Y) 
		 (YM ?X) 
  )
 :effect (probabilistic 
		 83/100 (and (not (OU ?X ?Y)) (not (VC ?Y)) )  
		 3/100 (and (YM ?Y) (not (VC ?Y)) (not (YM ?X)) (VC ?X) )  
		 1/100 (and (OU ?Z ?X) (not (SY ?X ?Z)) )  
		 13/100 (and (not (SY ?X ?Z)) )  
          )
 )
(:action XPX
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (OU ?Z ?X) 
		 (SY ?X ?X) 
		 (OU ?Z ?Y) 
  )
 :effect (probabilistic 
		 46/100 (and (not (SY ?X ?X)) )  
		 40/100 (and (YM ?X) (not (OU ?Z ?X)) )  
		 14/100 (and (not (OU ?Z ?X)) (not (SY ?X ?X)) (not (OU ?Z ?Y)) )  
          )
 )
(:action STX
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (VC ?X) 
		 (YM ?X) 
		 (OU ?Y ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (YM ?Z) (YM ?Y) (SY ?Y ?X) (SY ?Z ?Z) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (VC ?x)) 
      (not (OU ?x WI)) 
      (not (OU ?x UK)) 
      (not (OU ?x YB)) 
      (not (OU ?x ZJ)) 
      (not (OU ?x KO)) 
      (not (OU ?x AB)) 
      (not (OU ?x OE)) 
      (not (OU ?x MC)) 
      (not (OU ?x SQ)) 
      (not (OU ?x CH)) 
      (not (AZ ?x WI)) 
      (not (AZ ?x UK)) 
      (not (AZ ?x YB)) 
      (not (AZ ?x ZJ)) 
      (not (AZ ?x KO)) 
      (not (AZ ?x AB)) 
      (not (AZ ?x OE)) 
      (not (AZ ?x MC)) 
      (not (AZ ?x SQ)) 
      (not (AZ ?x CH)) 
      (not (SY ?x WI)) 
      (not (SY ?x UK)) 
      (not (SY ?x YB)) 
      (not (SY ?x ZJ)) 
      (not (SY ?x KO)) 
      (not (SY ?x AB)) 
      (not (SY ?x OE)) 
      (not (SY ?x MC)) 
      (not (SY ?x SQ)) 
      (not (SY ?x CH)) 
      (not (YM ?x)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(YM ZJ) 
(AZ YB SQ) 
(SY KO KO) 
(YM CH) 
(OU KO ZJ) 
(VC YB) 
(VC WI) 
(SY UK OE) 
(SY KO MC) 
(OU OE AB) 
(AZ SQ ZJ) 
(OU MC MC) 
(OU KO UK) 
(VC SQ) 
(SY OE KO) 
(AZ SQ SQ) 
(OU ZJ YB) 
(SY OE MC) 
(YM YB) 
(AZ SQ WI) 
(YM OE) 
(AZ ZJ KO) 
(OU UK YB) 
(VC ZJ) 
)))
