(define (problem random-problem720) 
 (:domain prob_domain) 
 (:init 
(not-clear)
(YM ZJ) (AZ YB SQ) (SY KO KO) (YM CH) (OU KO ZJ) (VC YB) (VC WI) (SY UK OE) (SY KO MC) (OU OE AB) (AZ SQ ZJ) (OU MC MC) (OU KO UK) (VC SQ) (SY OE KO) (AZ SQ SQ) (OU ZJ YB) (SY OE MC) (YM YB) (AZ SQ WI) (YM OE) (AZ ZJ KO) (OU UK YB) (VC ZJ)  
)
 (:goal (and 
(YM UK ) 
(SY UK  YB ) 
(SY CH  CH ) 
(YM MC ) 
(SY MC  MC ) 
(SY ZJ  YB ) 
(SY ZJ  ZJ ) 
(SY YB  YB ) 
(SY YB  ZJ ) 
(YM KO ) 
(SY KO  ZJ ) 
(YM AB ) 
(SY AB  AB ) 
(YM WI ) 
(SY WI  WI ) 
))
)
