(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants QL ND WZ KR WH SR BH LL BU TB )
 (:predicates 
	 (TK ?X ) 
	 (FZ ?X ) 
	 (YM ?X ?Y ) 
	 (TE ?X ?Y ) 
	 (LU ?X ) 
(clear)
(not-clear)
 )
(:action STR
 :parameters (?X ?Y )
 :precondition (and 
		 (TE ?X ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (TE ?Y ?Y) )  
          )
 )
(:action HWG
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (LU ?Z) 
		 (TK ?Z) 
		 (YM ?Z ?Y) 
		 (TK ?Y) 
		 (FZ ?Y) 
  )
 :effect (probabilistic 
		 60/100 (and (not (TK ?Y)) (not (TK ?Z)) (not (LU ?Z)) (not (YM ?Z ?Y)) (not (FZ ?Y)) )  
		 40/100 (and (not (LU ?Z)) (TK ?X) (not (TK ?Z)) (TE ?Z ?Y) )  
          )
 )
(:action XUP
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (LU ?X) 
		 (TK ?Z) 
  )
 :effect (probabilistic 
		 37/100 (and (not (LU ?X)) )  
		 51/100 (and (not (TK ?Z)) (not (LU ?X)) (TK ?Y) )  
		 9/100 (and (not (LU ?X)) (TK ?Y) )  
		 3/100 (and (FZ ?X) (TK ?Y) (not (TK ?Z)) (FZ ?Z) )  
          )
 )
(:action QDD
 :parameters (?X ?Y )
 :precondition (and 
		 (TE ?X ?X) 
		 (YM ?X ?Y) 
  )
 :effect (probabilistic 
		 92/100 (and (FZ ?Y) )  
		 3/100 (and (TE ?X ?Y) )  
		 3/100 (and (not (YM ?X ?Y)) (LU ?Y) )  
		 1/100 (and (LU ?X) (not (TE ?X ?X)) )  
		 1/100 (and (LU ?Y) (not (TE ?X ?X)) (not (YM ?X ?Y)) )  
          )
 )
(:action XZF
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (YM ?Y ?X) 
		 (TK ?Y) 
		 (LU ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (TK ?Y)) (TE ?Z ?Z) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (TK ?x)) 
      (not (FZ ?x)) 
      (not (YM ?x QL)) 
      (not (YM ?x ND)) 
      (not (YM ?x WZ)) 
      (not (YM ?x KR)) 
      (not (YM ?x WH)) 
      (not (YM ?x SR)) 
      (not (YM ?x BH)) 
      (not (YM ?x LL)) 
      (not (YM ?x BU)) 
      (not (YM ?x TB)) 
      (not (TE ?x QL)) 
      (not (TE ?x ND)) 
      (not (TE ?x WZ)) 
      (not (TE ?x KR)) 
      (not (TE ?x WH)) 
      (not (TE ?x SR)) 
      (not (TE ?x BH)) 
      (not (TE ?x LL)) 
      (not (TE ?x BU)) 
      (not (TE ?x TB)) 
      (not (LU ?x)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(TE ND ND) 
(LU BU) 
(FZ KR) 
(LU KR) 
(FZ WH) 
(TE ND SR) 
(FZ LL) 
(TE SR BU) 
(YM BU ND) 
(LU BH) 
(LU QL) 
(TE QL TB) 
(TE KR WZ) 
(LU ND) 
(TE LL ND) 
(YM KR WZ) 
(TE WH ND) 
(YM LL TB) 
(LU LL) 
(YM BU QL) 
(TE BH TB) 
(YM WZ QL) 
(YM BH BH) 
(YM WH KR) 
(TE BH BU) 
(YM BH WZ) 
(TE TB TB) 
(TE LL TB) 
)))
