(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants MV BS KE SA CT YC NW AI OI SM )
 (:predicates 
	 (BL ?X ?Y ) 
	 (WN ?X ?Y ) 
	 (EX ?X ?Y ) 
	 (GQ ?X ) 
	 (KW ?X ) 
(clear)
(not-clear)
 )
(:action RQQ
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (GQ ?Y) 
		 (EX ?X ?Z) 
		 (BL ?X ?X) 
		 (BL ?Y ?Z) 
  )
 :effect (probabilistic 
		 90/100 (and (not (EX ?X ?Z)) )  
		 4/100 (and (not (BL ?Y ?Z)) (GQ ?X) (BL ?X ?Y) )  
		 1/100 (and (not (EX ?X ?Z)) (not (BL ?Y ?Z)) )  
		 5/100 (and (not (BL ?X ?X)) )  
          )
 )
(:action BSM
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (EX ?X ?X) 
		 (BL ?Y ?Y) 
		 (KW ?X) 
		 (EX ?Y ?Z) 
		 (BL ?Z ?Y) 
  )
 :effect (probabilistic 
		 4/100 (and (not (BL ?Y ?Y)) )  
		 47/100 (and (WN ?Z ?Z) )  
		 0/100 (and (not (EX ?Y ?Z)) (KW ?Y) (not (BL ?Z ?Y)) (EX ?Y ?X) (WN ?Z ?Z) )  
		 3/100 (and (EX ?X ?Z) )  
		 46/100 (and (WN ?X ?Z) (not (BL ?Z ?Y)) )  
          )
 )
(:action PJJ
 :parameters (?X ?Y )
 :precondition (and 
		 (GQ ?X) 
		 (KW ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (GQ ?Y) (not (KW ?Y)) (BL ?Y ?Y) (WN ?X ?Y) )  
          )
 )
(:action FDR
 :parameters (?X ?Y )
 :precondition (and 
		 (BL ?Y ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (not (BL ?Y ?Y)) (EX ?X ?Y) )  
          )
 )
(:action WAA
 :parameters (?X ?Y )
 :precondition (and 
		 (WN ?Y ?Y) 
  )
 :effect (probabilistic 
		 33/100 (and (GQ ?X) (not (WN ?Y ?Y)) )  
		 67/100 (and (BL ?X ?X) (KW ?Y) (not (WN ?Y ?Y)) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (BL ?x MV)) 
      (not (BL ?x BS)) 
      (not (BL ?x KE)) 
      (not (BL ?x SA)) 
      (not (BL ?x CT)) 
      (not (BL ?x YC)) 
      (not (BL ?x NW)) 
      (not (BL ?x AI)) 
      (not (BL ?x OI)) 
      (not (BL ?x SM)) 
      (not (WN ?x MV)) 
      (not (WN ?x BS)) 
      (not (WN ?x KE)) 
      (not (WN ?x SA)) 
      (not (WN ?x CT)) 
      (not (WN ?x YC)) 
      (not (WN ?x NW)) 
      (not (WN ?x AI)) 
      (not (WN ?x OI)) 
      (not (WN ?x SM)) 
      (not (EX ?x MV)) 
      (not (EX ?x BS)) 
      (not (EX ?x KE)) 
      (not (EX ?x SA)) 
      (not (EX ?x CT)) 
      (not (EX ?x YC)) 
      (not (EX ?x NW)) 
      (not (EX ?x AI)) 
      (not (EX ?x OI)) 
      (not (EX ?x SM)) 
      (not (GQ ?x)) 
      (not (KW ?x)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(EX KE SA) 
(KW NW) 
(BL OI YC) 
(EX CT YC) 
(BL AI CT) 
(KW SA) 
(KW MV) 
(EX SA SA) 
(KW YC) 
(WN NW KE) 
(BL OI CT) 
(KW OI) 
(GQ BS) 
(GQ AI) 
(EX MV OI) 
(GQ CT) 
(EX MV SM) 
(WN CT SM) 
(BL SA SM) 
(EX SM CT) 
(BL BS NW) 
(WN BS KE) 
(BL BS YC) 
(WN CT YC) 
(BL NW YC) 
(BL MV SM) 
(BL MV MV) 
(BL SM AI) 
(BL OI NW) 
(WN KE SM) 
)))
