(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants SV KI RA PE FI HK JZ BR BZ IM )
 (:predicates 
	 (QH ?X ?Y ) 
	 (WE ?X ) 
	 (GS ?X ) 
	 (UO ?X ?Y ) 
	 (QJ ?X ) 
	 (OO ?X ?Y ) 
(clear)
(not-clear)
 )
(:action WUF
 :parameters (?X ?Y )
 :precondition (and 
		 (WE ?Y) 
		 (UO ?X ?X) 
  )
 :effect (probabilistic 
		 10/100 (and (not (UO ?X ?X)) (QH ?Y ?Y) (not (WE ?Y)) )  
		 90/100 (and (not (WE ?Y)) )  
          )
 )
(:action ZVU
 :parameters (?X ?Y )
 :precondition (and 
		 (WE ?Y) 
		 (UO ?X ?Y) 
		 (QJ ?X) 
		 (QJ ?Y) 
  )
 :effect (probabilistic 
		 49/100 (and (not (QJ ?Y)) (OO ?Y ?X) (not (QJ ?X)) )  
		 24/100 (and (not (QJ ?X)) (not (UO ?X ?Y)) (OO ?X ?Y) (UO ?X ?X) (not (WE ?Y)) )  
		 0/100 (and (not (WE ?Y)) )  
		 27/100 (and (OO ?X ?X) (not (UO ?X ?Y)) (not (WE ?Y)) )  
          )
 )
(:action VML
 :parameters (?X ?Y )
 :precondition (and 
		 (QH ?X ?Y) 
		 (UO ?Y ?Y) 
  )
 :effect (probabilistic 
		 99/100 (and (not (UO ?Y ?Y)) (GS ?Y) (QJ ?X) (not (QH ?X ?Y)) )  
		 1/100 (and (QJ ?Y) (not (QH ?X ?Y)) (OO ?Y ?Y) (not (UO ?Y ?Y)) (OO ?X ?X) )  
          )
 )
(:action YJJ
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (UO ?Z ?Y) 
		 (QH ?X ?Y) 
		 (WE ?Y) 
  )
 :effect (probabilistic 
		 12/100 (and (UO ?X ?Y) (not (UO ?Z ?Y)) (QH ?Z ?Y) (not (WE ?Y)) )  
		 4/100 (and (not (WE ?Y)) )  
		 28/100 (and (QJ ?Y) )  
		 56/100 (and (OO ?X ?Z) (not (QH ?X ?Y)) (not (UO ?Z ?Y)) (not (WE ?Y)) )  
          )
 )
(:action SQH
 :parameters (?X ?Y )
 :precondition (and 
		 (QH ?Y ?X) 
  )
 :effect (probabilistic 
		 48/100 (and (GS ?X) (not (QH ?Y ?X)) (GS ?Y) )  
		 52/100 (and (GS ?X) (OO ?Y ?Y) )  
          )
 )
(:action DVL
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (QH ?Z ?Y) 
		 (WE ?Y) 
		 (QH ?Z ?Z) 
		 (QH ?Y ?Z) 
		 (UO ?Z ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (UO ?Y ?Z) (not (QH ?Z ?Z)) (not (WE ?Y)) (QJ ?Z) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (QH ?x SV)) 
      (not (QH ?x KI)) 
      (not (QH ?x RA)) 
      (not (QH ?x PE)) 
      (not (QH ?x FI)) 
      (not (QH ?x HK)) 
      (not (QH ?x JZ)) 
      (not (QH ?x BR)) 
      (not (QH ?x BZ)) 
      (not (QH ?x IM)) 
      (not (WE ?x)) 
      (not (GS ?x)) 
      (not (UO ?x SV)) 
      (not (UO ?x KI)) 
      (not (UO ?x RA)) 
      (not (UO ?x PE)) 
      (not (UO ?x FI)) 
      (not (UO ?x HK)) 
      (not (UO ?x JZ)) 
      (not (UO ?x BR)) 
      (not (UO ?x BZ)) 
      (not (UO ?x IM)) 
      (not (QJ ?x)) 
      (not (OO ?x SV)) 
      (not (OO ?x KI)) 
      (not (OO ?x RA)) 
      (not (OO ?x PE)) 
      (not (OO ?x FI)) 
      (not (OO ?x HK)) 
      (not (OO ?x JZ)) 
      (not (OO ?x BR)) 
      (not (OO ?x BZ)) 
      (not (OO ?x IM)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(UO PE BZ) 
(QH FI BZ) 
(QH IM SV) 
(OO HK BZ) 
(GS PE) 
(OO PE BZ) 
(QH RA KI) 
(GS BR) 
(UO IM JZ) 
(QJ BZ) 
(GS BZ) 
(WE KI) 
(QH KI BR) 
(OO BR JZ) 
(UO FI RA) 
(OO BZ BR) 
(GS RA) 
(OO IM JZ) 
(OO KI IM) 
(GS JZ) 
(OO SV FI) 
(GS IM) 
(UO IM HK) 
(OO BR FI) 
(QH PE KI) 
(UO BR KI) 
(UO HK KI) 
(OO RA SV) 
(QH IM BZ) 
(UO HK JZ) 
(QH JZ RA) 
(QH BR FI) 
(QH FI BR) 
(UO IM IM) 
)))
