(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants AH IK KU XC WL FD CL VY NM NL )
 (:predicates 
	 (QG ?X ) 
	 (VP ?X ?Y ) 
	 (OV ?X ) 
	 (ZY ?X ?Y ) 
	 (HO ?X ?Y ) 
	 (GN ?X ?Y ) 
(clear)
(not-clear)
 )
(:action FKL
 :parameters (?X ?Y )
 :precondition (and 
		 (GN ?Y ?Y) 
		 (OV ?X) 
		 (HO ?X ?Y) 
		 (GN ?X ?X) 
		 (QG ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (VP ?X ?X) )  
          )
 )
(:action IQC
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (QG ?Z) 
		 (ZY ?Z ?X) 
		 (OV ?X) 
  )
 :effect (probabilistic 
		 13/100 (and (not (QG ?Z)) (VP ?Z ?Y) (not (OV ?X)) (GN ?Z ?Z) )  
		 87/100 (and (not (QG ?Z)) )  
          )
 )
(:action QZO
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (HO ?Z ?X) 
		 (HO ?X ?Z) 
		 (QG ?X) 
		 (VP ?X ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (HO ?X ?Z)) (QG ?Y) (ZY ?X ?Y) )  
          )
 )
(:action YZJ
 :parameters (?X )
 :precondition (and 
		 (OV ?X) 
		 (GN ?X ?X) 
		 (HO ?X ?X) 
		 (QG ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (QG ?X)) (VP ?X ?X) (not (GN ?X ?X)) (not (HO ?X ?X)) )  
          )
 )
(:action NTE
 :parameters (?X )
 :precondition (and 
		 (OV ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (HO ?X ?X) (not (OV ?X)) )  
          )
 )
(:action VCY
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (ZY ?X ?Z) 
		 (VP ?Y ?X) 
		 (OV ?Z) 
		 (ZY ?Z ?X) 
  )
 :effect (probabilistic 
		 26/100 (and (not (OV ?Z)) (not (ZY ?Z ?X)) )  
		 28/100 (and (not (OV ?Z)) (not (ZY ?Z ?X)) (QG ?Y) (not (VP ?Y ?X)) (VP ?Z ?Y) (OV ?Y) )  
		 39/100 (and (not (OV ?Z)) (not (VP ?Y ?X)) (ZY ?Z ?Z) )  
		 2/100 (and (HO ?X ?Z) (HO ?X ?X) (not (VP ?Y ?X)) )  
		 5/100 (and (VP ?X ?X) (QG ?X) (VP ?Z ?X) (HO ?Y ?X) (HO ?X ?Z) (not (ZY ?Z ?X)) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (QG ?x)) 
      (not (VP ?x AH)) 
      (not (VP ?x IK)) 
      (not (VP ?x KU)) 
      (not (VP ?x XC)) 
      (not (VP ?x WL)) 
      (not (VP ?x FD)) 
      (not (VP ?x CL)) 
      (not (VP ?x VY)) 
      (not (VP ?x NM)) 
      (not (VP ?x NL)) 
      (not (OV ?x)) 
      (not (ZY ?x AH)) 
      (not (ZY ?x IK)) 
      (not (ZY ?x KU)) 
      (not (ZY ?x XC)) 
      (not (ZY ?x WL)) 
      (not (ZY ?x FD)) 
      (not (ZY ?x CL)) 
      (not (ZY ?x VY)) 
      (not (ZY ?x NM)) 
      (not (ZY ?x NL)) 
      (not (HO ?x AH)) 
      (not (HO ?x IK)) 
      (not (HO ?x KU)) 
      (not (HO ?x XC)) 
      (not (HO ?x WL)) 
      (not (HO ?x FD)) 
      (not (HO ?x CL)) 
      (not (HO ?x VY)) 
      (not (HO ?x NM)) 
      (not (HO ?x NL)) 
      (not (GN ?x AH)) 
      (not (GN ?x IK)) 
      (not (GN ?x KU)) 
      (not (GN ?x XC)) 
      (not (GN ?x WL)) 
      (not (GN ?x FD)) 
      (not (GN ?x CL)) 
      (not (GN ?x VY)) 
      (not (GN ?x NM)) 
      (not (GN ?x NL)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(OV NM) 
(QG IK) 
(VP NL WL) 
(GN WL CL) 
(HO NL AH) 
(ZY XC KU) 
(ZY KU WL) 
(GN IK WL) 
(HO IK VY) 
(ZY NL CL) 
(GN VY CL) 
(QG FD) 
(HO IK CL) 
(GN VY VY) 
(HO WL KU) 
(ZY CL XC) 
(QG VY) 
(ZY FD NM) 
(GN KU AH) 
(HO VY NL) 
(VP IK CL) 
(GN IK XC) 
(VP KU KU) 
(HO IK NL) 
(OV FD) 
(VP IK IK) 
(QG CL) 
(QG KU) 
(VP FD NM) 
(ZY WL KU) 
(ZY AH IK) 
(VP XC KU) 
(GN WL FD) 
(ZY FD NL) 
(ZY KU IK) 
(OV WL) 
(QG AH) 
(OV VY) 
)))
