(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants SF AA XI YL DQ PF MF QO TQ XE )
 (:predicates 
	 (GC ?X ?Y ) 
	 (VY ?X ) 
	 (WN ?X ) 
	 (LT ?X ) 
	 (FY ?X ) 
	 (TU ?X ?Y ) 
(clear)
(not-clear)
 )
(:action HOC
 :parameters (?X )
 :precondition (and 
		 (VY ?X) 
  )
 :effect (probabilistic 
		 42/100 (and (not (VY ?X)) )  
		 58/100 (and (WN ?X) (not (VY ?X)) )  
          )
 )
(:action JAC
 :parameters (?X ?Y )
 :precondition (and 
		 (FY ?X) 
		 (VY ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (TU ?X ?Y) (LT ?Y) (not (VY ?Y)) (LT ?X) )  
          )
 )
(:action BQI
 :parameters (?X )
 :precondition (and 
		 (VY ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (VY ?X)) (GC ?X ?X) )  
          )
 )
(:action VTD
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (LT ?X) 
		 (GC ?Z ?Y) 
		 (WN ?Z) 
		 (VY ?Y) 
		 (VY ?Z) 
  )
 :effect (probabilistic 
		 100/100 (and (not (WN ?Z)) )  
          )
 )
(:action HSA
 :parameters (?X )
 :precondition (and 
		 (WN ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (LT ?X) (not (WN ?X)) (VY ?X) )  
          )
 )
(:action BBP
 :parameters (?X )
 :precondition (and 
		 (FY ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (FY ?X)) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (GC ?x SF)) 
      (not (GC ?x AA)) 
      (not (GC ?x XI)) 
      (not (GC ?x YL)) 
      (not (GC ?x DQ)) 
      (not (GC ?x PF)) 
      (not (GC ?x MF)) 
      (not (GC ?x QO)) 
      (not (GC ?x TQ)) 
      (not (GC ?x XE)) 
      (not (VY ?x)) 
      (not (WN ?x)) 
      (not (LT ?x)) 
      (not (FY ?x)) 
      (not (TU ?x SF)) 
      (not (TU ?x AA)) 
      (not (TU ?x XI)) 
      (not (TU ?x YL)) 
      (not (TU ?x DQ)) 
      (not (TU ?x PF)) 
      (not (TU ?x MF)) 
      (not (TU ?x QO)) 
      (not (TU ?x TQ)) 
      (not (TU ?x XE)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(FY QO) 
(FY PF) 
(LT YL) 
(WN XI) 
(VY YL) 
(VY AA) 
(LT DQ) 
(WN SF) 
(WN MF) 
(GC AA AA) 
(WN DQ) 
(LT SF) 
(TU AA AA) 
(TU SF TQ) 
(LT PF) 
(FY SF) 
(FY AA) 
(GC XI MF) 
(FY MF) 
(LT TQ) 
(TU XI TQ) 
(LT MF) 
(TU XI XI) 
(VY SF) 
(LT QO) 
(TU TQ XE) 
(LT AA) 
(FY YL) 
(GC PF YL) 
(WN QO) 
(GC XI TQ) 
(FY XI) 
(TU AA YL) 
(GC DQ TQ) 
(LT XE) 
(GC TQ XI) 
(VY PF) 
(WN XE) 
(GC XE XE) 
(WN TQ) 
)))
