(define (problem random-problem374) 
 (:domain prob_domain) 
 (:init 
(not-clear)
(FY QO) (FY PF) (LT YL) (WN XI) (VY YL) (VY AA) (LT DQ) (WN SF) (WN MF) (GC AA AA) (WN DQ) (LT SF) (TU AA AA) (TU SF TQ) (LT PF) (FY SF) (FY AA) (GC XI MF) (FY MF) (LT TQ) (TU XI TQ) (LT MF) (TU XI XI) (VY SF) (LT QO) (TU TQ XE) (LT AA) (FY YL) (GC PF YL) (WN QO) (GC XI TQ) (FY XI) (TU AA YL) (GC DQ TQ) (LT XE) (GC TQ XI) (VY PF) (WN XE) (GC XE XE) (WN TQ)  
)
 (:goal (and 
(TU MF  PF ) 
(TU AA  SF ) 
(TU PF  AA ) 
(TU MF  SF ) 
(LT XI ) 
(TU YL  QO ) 
(TU SF  XE ) 
(TU QO  MF ) 
(TU MF  XI ) 
(TU XI  DQ ) 
(TU MF  YL ) 
))
)
