(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants VR VX YD GO PN TE TJ FH OM HL )
 (:predicates 
	 (VQ ?X ?Y ) 
	 (UA ?X ?Y ) 
	 (LT ?X ?Y ) 
	 (AD ?X ) 
	 (GB ?X ) 
	 (SE ?X ) 
(clear)
(not-clear)
 )
(:action OZV
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (UA ?X ?Z) 
		 (SE ?Z) 
  )
 :effect (probabilistic 
		 22/100 (and (not (UA ?X ?Z)) (AD ?Z) )  
		 78/100 (and (VQ ?Y ?Z) (LT ?Z ?Y) (UA ?Z ?Y) (GB ?Z) (SE ?X) )  
          )
 )
(:action XWM
 :parameters (?X ?Y )
 :precondition (and 
		 (GB ?X) 
		 (AD ?Y) 
		 (SE ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (SE ?Y) (not (SE ?X)) )  
          )
 )
(:action MRR
 :parameters (?X ?Y )
 :precondition (and 
		 (GB ?Y) 
		 (SE ?Y) 
		 (VQ ?Y ?Y) 
		 (VQ ?X ?Y) 
		 (UA ?Y ?Y) 
  )
 :effect (probabilistic 
		 47/100 (and (SE ?X) (not (UA ?Y ?Y)) )  
		 53/100 (and (not (VQ ?Y ?Y)) )  
          )
 )
(:action NGN
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (VQ ?Z ?Z) 
		 (GB ?Y) 
		 (LT ?Y ?X) 
		 (LT ?Z ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (UA ?Z ?Z) (LT ?Y ?Z) (not (VQ ?Z ?Z)) )  
          )
 )
(:action CMZ
 :parameters (?X ?Y )
 :precondition (and 
		 (UA ?Y ?X) 
		 (VQ ?Y ?Y) 
		 (GB ?X) 
		 (SE ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (not (GB ?X)) (VQ ?X ?Y) (AD ?Y) (not (SE ?Y)) )  
          )
 )
(:action HIU
 :parameters (?X ?Y )
 :precondition (and 
		 (GB ?X) 
		 (GB ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (not (GB ?Y)) )  
          )
 )
(:action PGX
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (AD ?X) 
		 (VQ ?X ?Z) 
		 (VQ ?X ?X) 
		 (VQ ?Y ?Z) 
  )
 :effect (probabilistic 
		 100/100 (and (not (AD ?X)) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (VQ ?x VR)) 
      (not (VQ ?x VX)) 
      (not (VQ ?x YD)) 
      (not (VQ ?x GO)) 
      (not (VQ ?x PN)) 
      (not (VQ ?x TE)) 
      (not (VQ ?x TJ)) 
      (not (VQ ?x FH)) 
      (not (VQ ?x OM)) 
      (not (VQ ?x HL)) 
      (not (UA ?x VR)) 
      (not (UA ?x VX)) 
      (not (UA ?x YD)) 
      (not (UA ?x GO)) 
      (not (UA ?x PN)) 
      (not (UA ?x TE)) 
      (not (UA ?x TJ)) 
      (not (UA ?x FH)) 
      (not (UA ?x OM)) 
      (not (UA ?x HL)) 
      (not (LT ?x VR)) 
      (not (LT ?x VX)) 
      (not (LT ?x YD)) 
      (not (LT ?x GO)) 
      (not (LT ?x PN)) 
      (not (LT ?x TE)) 
      (not (LT ?x TJ)) 
      (not (LT ?x FH)) 
      (not (LT ?x OM)) 
      (not (LT ?x HL)) 
      (not (AD ?x)) 
      (not (GB ?x)) 
      (not (SE ?x)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(AD GO) 
(GB YD) 
(LT OM FH) 
(LT FH HL) 
(LT TJ OM) 
(AD YD) 
(GB FH) 
(VQ TJ PN) 
(SE TJ) 
(UA YD TJ) 
(LT OM OM) 
(UA PN VX) 
(VQ OM VX) 
(AD TJ) 
(UA GO TJ) 
(SE VX) 
(AD FH) 
(GB HL) 
(LT VR GO) 
(VQ OM OM) 
(UA YD PN) 
(LT TJ FH) 
(LT TJ VR) 
(SE TE) 
(GB PN) 
(LT OM VX) 
(VQ FH OM) 
(LT VR VR) 
(GB TE) 
(SE HL) 
(SE OM) 
(AD HL) 
(UA HL VX) 
(LT VX TE) 
(UA TE OM) 
(AD VX) 
(VQ HL PN) 
(UA HL HL) 
(LT VX GO) 
(LT HL VR) 
(SE PN) 
(LT TE FH) 
)))
