(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants XG EW VC YI UP FR KX LY AB QF )
 (:predicates 
	 (VW ?X ) 
	 (BO ?X ?Y ) 
	 (WY ?X ?Y ) 
	 (GX ?X ?Y ) 
	 (PC ?X ?Y ) 
	 (DX ?X ?Y ) 
	 (FW ?X ) 
(clear)
(not-clear)
 )
(:action XXK
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (PC ?X ?Y) 
		 (VW ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (PC ?X ?Y)) (not (VW ?X)) (VW ?Y) (GX ?Z ?Y) )  
          )
 )
(:action DGC
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (GX ?Y ?Z) 
		 (DX ?X ?Z) 
		 (DX ?X ?X) 
  )
 :effect (probabilistic 
		 26/100 (and (not (DX ?X ?Z)) (FW ?Y) (PC ?Z ?Z) (not (DX ?X ?X)) )  
		 57/100 (and (not (DX ?X ?Z)) (not (DX ?X ?X)) (GX ?Y ?X) (GX ?Z ?Y) (FW ?Z) (WY ?Z ?X) )  
		 17/100 (and (not (DX ?X ?X)) (not (GX ?Y ?Z)) )  
          )
 )
(:action KUW
 :parameters (?X ?Y )
 :precondition (and 
		 (FW ?Y) 
		 (GX ?X ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (not (FW ?Y)) (DX ?X ?Y) )  
          )
 )
(:action KBS
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (FW ?Y) 
		 (WY ?Y ?Z) 
		 (FW ?Z) 
		 (DX ?Z ?Z) 
		 (BO ?Y ?X) 
		 (PC ?Y ?Y) 
  )
 :effect (probabilistic 
		 56/100 (and (VW ?Y) (not (DX ?Z ?Z)) )  
		 13/100 (and (not (FW ?Z)) (WY ?Y ?Y) (VW ?X) (DX ?Z ?Y) (GX ?Z ?X) (VW ?Z) )  
		 6/100 (and (WY ?Z ?Z) (DX ?X ?Z) (PC ?Z ?X) (not (WY ?Y ?Z)) )  
		 25/100 (and (VW ?Y) (not (PC ?Y ?Y)) )  
          )
 )
(:action NOB
 :parameters (?X ?Y )
 :precondition (and 
		 (GX ?X ?Y) 
		 (PC ?X ?X) 
		 (DX ?Y ?Y) 
		 (PC ?Y ?Y) 
  )
 :effect (probabilistic 
		 100/100 (and (not (GX ?X ?Y)) )  
          )
 )
(:action YFZ
 :parameters (?X )
 :precondition (and 
		 (DX ?X ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (DX ?X ?X)) )  
          )
 )
(:action FIO
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (VW ?Y) 
		 (BO ?Z ?X) 
		 (FW ?X) 
		 (WY ?Y ?Z) 
		 (WY ?X ?X) 
  )
 :effect (probabilistic 
		 15/100 (and (DX ?X ?Y) (not (VW ?Y)) (not (FW ?X)) (PC ?X ?Y) (not (BO ?Z ?X)) )  
		 85/100 (and (WY ?Y ?X) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (VW ?x)) 
      (not (BO ?x XG)) 
      (not (BO ?x EW)) 
      (not (BO ?x VC)) 
      (not (BO ?x YI)) 
      (not (BO ?x UP)) 
      (not (BO ?x FR)) 
      (not (BO ?x KX)) 
      (not (BO ?x LY)) 
      (not (BO ?x AB)) 
      (not (BO ?x QF)) 
      (not (WY ?x XG)) 
      (not (WY ?x EW)) 
      (not (WY ?x VC)) 
      (not (WY ?x YI)) 
      (not (WY ?x UP)) 
      (not (WY ?x FR)) 
      (not (WY ?x KX)) 
      (not (WY ?x LY)) 
      (not (WY ?x AB)) 
      (not (WY ?x QF)) 
      (not (GX ?x XG)) 
      (not (GX ?x EW)) 
      (not (GX ?x VC)) 
      (not (GX ?x YI)) 
      (not (GX ?x UP)) 
      (not (GX ?x FR)) 
      (not (GX ?x KX)) 
      (not (GX ?x LY)) 
      (not (GX ?x AB)) 
      (not (GX ?x QF)) 
      (not (PC ?x XG)) 
      (not (PC ?x EW)) 
      (not (PC ?x VC)) 
      (not (PC ?x YI)) 
      (not (PC ?x UP)) 
      (not (PC ?x FR)) 
      (not (PC ?x KX)) 
      (not (PC ?x LY)) 
      (not (PC ?x AB)) 
      (not (PC ?x QF)) 
      (not (DX ?x XG)) 
      (not (DX ?x EW)) 
      (not (DX ?x VC)) 
      (not (DX ?x YI)) 
      (not (DX ?x UP)) 
      (not (DX ?x FR)) 
      (not (DX ?x KX)) 
      (not (DX ?x LY)) 
      (not (DX ?x AB)) 
      (not (DX ?x QF)) 
      (not (FW ?x)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(VW FR) 
(GX VC EW) 
(BO VC AB) 
(VW EW) 
(PC FR FR) 
(BO AB QF) 
(BO XG QF) 
(WY EW YI) 
(WY XG XG) 
(PC AB AB) 
(FW UP) 
(WY FR XG) 
(GX AB YI) 
(PC VC EW) 
(PC YI YI) 
(GX XG FR) 
(FW QF) 
(FW XG) 
(FW EW) 
(WY UP UP) 
(VW KX) 
(GX YI UP) 
(BO AB XG) 
(DX AB YI) 
(BO YI VC) 
(GX UP KX) 
(BO QF KX) 
(PC KX KX) 
(WY LY KX) 
(BO XG XG) 
(WY UP YI) 
(WY XG LY) 
(BO XG FR) 
(BO FR FR) 
(DX EW AB) 
(PC XG UP) 
(DX EW FR) 
(BO UP EW) 
(WY AB XG) 
(WY UP XG) 
(WY FR UP) 
(PC EW KX) 
(PC FR AB) 
(WY LY UP) 
)))
