(define (domain prob_domain) 
 (:requirements :strips :probabilistic-effects :conditional-effects) 
 (:constants TF GA BB VA GL NL YQ ZA LM NJ )
 (:predicates 
	 (TQ ?X ) 
	 (TA ?X ?Y ) 
	 (GD ?X ) 
	 (QK ?X ) 
	 (XG ?X ) 
	 (CY ?X ) 
	 (ET ?X ?Y ) 
(clear)
(not-clear)
 )
(:action TQK
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (ET ?X ?Y) 
		 (TA ?Y ?X) 
		 (TQ ?Y) 
		 (QK ?Y) 
		 (TA ?Z ?Z) 
		 (QK ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (TQ ?Y)) (not (ET ?X ?Y)) (ET ?X ?X) (not (TA ?Y ?X)) (TQ ?Z) )  
          )
 )
(:action PWS
 :parameters (?X )
 :precondition (and 
		 (TA ?X ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (GD ?X) (not (TA ?X ?X)) (ET ?X ?X) (XG ?X) (QK ?X) )  
          )
 )
(:action EVY
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (QK ?Z) 
		 (CY ?Y) 
		 (TQ ?Z) 
		 (GD ?Z) 
  )
 :effect (probabilistic 
		 71/100 (and (not (CY ?Y)) (not (QK ?Z)) (XG ?Z) )  
		 29/100 (and (ET ?Z ?X) )  
          )
 )
(:action QDI
 :parameters (?X ?Y )
 :precondition (and 
		 (CY ?Y) 
		 (ET ?X ?X) 
		 (QK ?X) 
		 (TQ ?Y) 
  )
 :effect (probabilistic 
		 75/100 (and (GD ?Y) )  
		 25/100 (and (XG ?X) )  
          )
 )
(:action BSX
 :parameters (?X )
 :precondition (and 
		 (XG ?X) 
		 (QK ?X) 
  )
 :effect (probabilistic 
		 100/100 (and (not (QK ?X)) (not (XG ?X)) )  
          )
 )
(:action AAR
 :parameters (?X ?Y ?Z )
 :precondition (and 
		 (QK ?X) 
		 (GD ?Z) 
		 (TQ ?Z) 
  )
 :effect (probabilistic 
		 100/100 (and (XG ?Y) (ET ?Y ?X) )  
          )
 )
(:action DFM
 :parameters (?X ?Y )
 :precondition (and 
		 (QK ?X) 
		 (ET ?Y ?X) 
  )
 :effect (probabilistic 
		 60/100 (and (not (QK ?X)) )  
		 40/100 (and (not (QK ?X)) (GD ?X) )  
          )
 )
(:action reset1 
 :precondition (not-clear)
 :effect (and 
	     (forall (?x) (and 
      (not (TQ ?x)) 
      (not (TA ?x TF)) 
      (not (TA ?x GA)) 
      (not (TA ?x BB)) 
      (not (TA ?x VA)) 
      (not (TA ?x GL)) 
      (not (TA ?x NL)) 
      (not (TA ?x YQ)) 
      (not (TA ?x ZA)) 
      (not (TA ?x LM)) 
      (not (TA ?x NJ)) 
      (not (GD ?x)) 
      (not (QK ?x)) 
      (not (XG ?x)) 
      (not (CY ?x)) 
      (not (ET ?x TF)) 
      (not (ET ?x GA)) 
      (not (ET ?x BB)) 
      (not (ET ?x VA)) 
      (not (ET ?x GL)) 
      (not (ET ?x NL)) 
      (not (ET ?x YQ)) 
      (not (ET ?x ZA)) 
      (not (ET ?x LM)) 
      (not (ET ?x NJ)) 
))
(not (not-clear))
(clear)))

(:action reset2 
 :precondition (clear) 
 :effect (and (not-clear)
              (not (clear))
(TA ZA GA) 
(GD NL) 
(CY GA) 
(XG TF) 
(ET TF LM) 
(TA NL BB) 
(GD GL) 
(TQ TF) 
(CY NL) 
(XG NL) 
(TA VA BB) 
(TQ YQ) 
(XG LM) 
(XG GL) 
(GD VA) 
(CY VA) 
(ET GA BB) 
(TA YQ GL) 
(ET VA NJ) 
(ET ZA GL) 
(CY TF) 
(TA BB NJ) 
(XG VA) 
(TA VA VA) 
(XG ZA) 
(QK ZA) 
(TA TF TF) 
(TQ VA) 
(ET LM BB) 
(CY NJ) 
(GD TF) 
(CY GL) 
(ET YQ ZA) 
(TQ LM) 
(QK VA) 
(XG YQ) 
(TA VA TF) 
(QK NL) 
(CY YQ) 
(ET LM LM) 
(GD ZA) 
(TQ GL) 
(TA TF GA) 
(TQ ZA) 
(ET GL GL) 
(TA ZA GL) 
)))
