(define (problem random-problem975) 
 (:domain prob_domain) 
 (:init 
(not-clear)
(TA ZA GA) (GD NL) (CY GA) (XG TF) (ET TF LM) (TA NL BB) (GD GL) (TQ TF) (CY NL) (XG NL) (TA VA BB) (TQ YQ) (XG LM) (XG GL) (GD VA) (CY VA) (ET GA BB) (TA YQ GL) (ET VA NJ) (ET ZA GL) (CY TF) (TA BB NJ) (XG VA) (TA VA VA) (XG ZA) (QK ZA) (TA TF TF) (TQ VA) (ET LM BB) (CY NJ) (GD TF) (CY GL) (ET YQ ZA) (TQ LM) (QK VA) (XG YQ) (TA VA TF) (QK NL) (CY YQ) (ET LM LM) (GD ZA) (TQ GL) (TA TF GA) (TQ ZA) (ET GL GL) (TA ZA GL)  
)
 (:goal (and 
(ET YQ  NL ) 
(XG GA ) 
(ET GA  ZA ) 
(XG NJ ) 
(ET NJ  NL ) 
(ET VA  VA ) 
(ET ZA  NL ) 
(ET GL  VA ) 
(ET NL  NL ) 
))
)
