(define (problem sysadmin-ssp-4-1-14123)
  (:domain sysadmin-ssp)
  (:init (all-updated))
  (:goal (and
    (all-updated)
    (running computer0)
    (running computer1)
    (running computer2)
    (running computer3)
  ))
  (:metric minimize (total-cost))
)
