(define (problem sysadmin-ssp-5-5-31353)
  (:domain sysadmin-ssp)
  (:init (all-updated))
  (:goal (and
    (all-updated)
    (running computer0)
    (running computer1)
    (running computer2)
    (running computer3)
    (running computer4)
  ))
  (:metric minimize (total-cost))
)
