(define (problem sysadmin-ssp-9-43-27160)
  (:domain sysadmin-ssp)
  (:init (all-updated))
  (:goal (and
    (all-updated)
    (running computer0)
    (running computer1)
    (running computer2)
    (running computer3)
    (running computer4)
    (running computer5)
    (running computer6)
    (running computer7)
    (running computer8)
  ))
  (:metric minimize (total-cost))
)
