(define (problem sysadmin-ssp-13-101-24043)
  (:domain sysadmin-ssp)
  (:init (all-updated))
  (:goal (and
    (all-updated)
    (running computer0)
    (running computer1)
    (running computer2)
    (running computer3)
    (running computer4)
    (running computer5)
    (running computer6)
    (running computer7)
    (running computer8)
    (running computer9)
    (running computer10)
    (running computer11)
    (running computer12)
  ))
  (:metric minimize (total-cost))
)
