(define (problem zeno_3_2_3_12861)
  (:domain zenotravel)
  (:objects c0 c1 c2 - city p0 p1 - person a0 a1 a2 - aircraft f0 f1 f2 f3 f4 - flevel)
  (:init (next f0 f1) (next f1 f2) (next f2 f3) (next f3 f4)
         (at-person p0 c2) (not-boarding p0) (not-debarking p0)
         (at-person p1 c2) (not-boarding p1) (not-debarking p1)
         (at-aircraft a0 c2) (fuel-level a0 f3) (not-refueling a0)
         (at-aircraft a1 c2) (fuel-level a1 f4) (not-refueling a1)
         (at-aircraft a2 c2) (fuel-level a2 f2) (not-refueling a2)
  )
  (:goal (and (at-person p0 c1) (at-person p1 c0)))
)
