(define (problem zeno_5_5_5_24164)
  (:domain zenotravel)
  (:objects c0 c1 c2 c3 c4 - city p0 p1 p2 p3 p4 - person a0 a1 a2 a3 a4 - aircraft f0 f1 f2 f3 f4 - flevel)
  (:init (next f0 f1) (next f1 f2) (next f2 f3) (next f3 f4)
         (at-person p0 c1) (not-boarding p0) (not-debarking p0)
         (at-person p1 c4) (not-boarding p1) (not-debarking p1)
         (at-person p2 c1) (not-boarding p2) (not-debarking p2)
         (at-person p3 c4) (not-boarding p3) (not-debarking p3)
         (at-person p4 c4) (not-boarding p4) (not-debarking p4)
         (at-aircraft a0 c4) (fuel-level a0 f4) (not-refueling a0)
         (at-aircraft a1 c2) (fuel-level a1 f1) (not-refueling a1)
         (at-aircraft a2 c3) (fuel-level a2 f1) (not-refueling a2)
         (at-aircraft a3 c2) (fuel-level a3 f2) (not-refueling a3)
         (at-aircraft a4 c1) (fuel-level a4 f0) (not-refueling a4)
  )
  (:goal (and (at-person p0 c2) (at-person p1 c2) (at-person p2 c3) (at-person p3 c2) (at-person p4 c4)))
)
