(define (problem zeno_6_6_6_24874)
  (:domain zenotravel)
  (:objects c0 c1 c2 c3 c4 c5 - city p0 p1 p2 p3 p4 p5 - person a0 a1 a2 a3 a4 a5 - aircraft f0 f1 f2 f3 f4 - flevel)
  (:init (next f0 f1) (next f1 f2) (next f2 f3) (next f3 f4)
         (at-person p0 c3) (not-boarding p0) (not-debarking p0)
         (at-person p1 c1) (not-boarding p1) (not-debarking p1)
         (at-person p2 c2) (not-boarding p2) (not-debarking p2)
         (at-person p3 c5) (not-boarding p3) (not-debarking p3)
         (at-person p4 c1) (not-boarding p4) (not-debarking p4)
         (at-person p5 c0) (not-boarding p5) (not-debarking p5)
         (at-aircraft a0 c5) (fuel-level a0 f4) (not-refueling a0)
         (at-aircraft a1 c3) (fuel-level a1 f3) (not-refueling a1)
         (at-aircraft a2 c3) (fuel-level a2 f3) (not-refueling a2)
         (at-aircraft a3 c3) (fuel-level a3 f2) (not-refueling a3)
         (at-aircraft a4 c1) (fuel-level a4 f1) (not-refueling a4)
         (at-aircraft a5 c2) (fuel-level a5 f3) (not-refueling a5)
  )
  (:goal (and (at-person p0 c3) (at-person p1 c4) (at-person p2 c3) (at-person p3 c4) (at-person p4 c3) (at-person p5 c3)))
)
