(define (problem p01)
  (:domain p01-dom)
  (:objects )
  (:init 
         (current-phase Arrivals-and-updating)
         (current-timestep U0)
         (need-to-process-arrivals C0)
         (available P0)
         (available P1)
         (available P2)
         (next-timestep U0 U1)
         (next-timestep U1 U2)
         (next-timestep U2 U3)
         (next-timestep U3 U4)
         (next-timestep U4 U5)
         (next-timestep U5 U6)
         (next-timestep U6 U7)
         (next-timestep U7 U8)
         (next-timestep U8 U9)
         (next-timestep U9 U10)
         (next-timestep U10 U0)
  )
  (:goal (and
      (served C0)
  ))
  (:metric minimize (total-cost))
)
