(define (problem p04)
  (:domain p04-dom)
  (:objects )
  (:init 
         (current-phase Arrivals-and-updating)
         (current-timestep U0)
         (need-to-process-arrivals C0)
         (available P0)
         (available P1)
         (available P2)
         (available P3)
         (available P4)
         (available P5)
         (next-timestep U0 U1)
         (next-timestep U1 U2)
         (next-timestep U2 U3)
         (next-timestep U3 U4)
         (next-timestep U4 U5)
         (next-timestep U5 U6)
         (next-timestep U6 U7)
         (next-timestep U7 U8)
         (next-timestep U8 U9)
         (next-timestep U9 U10)
         (next-timestep U10 U11)
         (next-timestep U11 U12)
         (next-timestep U12 U13)
         (next-timestep U13 U14)
         (next-timestep U14 U15)
         (next-timestep U15 U16)
         (next-timestep U16 U17)
         (next-timestep U17 U18)
         (next-timestep U18 U19)
         (next-timestep U19 U20)
         (next-timestep U20 U21)
         (next-timestep U21 U22)
         (next-timestep U22 U23)
         (next-timestep U23 U24)
         (next-timestep U24 U25)
         (next-timestep U25 U26)
         (next-timestep U26 U27)
         (next-timestep U27 U28)
         (next-timestep U28 U29)
         (next-timestep U29 U30)
         (next-timestep U30 U31)
         (next-timestep U31 U32)
         (next-timestep U32 U33)
         (next-timestep U33 U34)
         (next-timestep U34 U35)
         (next-timestep U35 U36)
         (next-timestep U36 U37)
         (next-timestep U37 U38)
         (next-timestep U38 U39)
         (next-timestep U39 U40)
         (next-timestep U40 U0)
  )
  (:goal (and
      (served C0)
  ))
  (:metric minimize (total-cost))
)
